const React = require("react-native");

const { StyleSheet } = React;

const { Dimensions, Platform } = React;
const deviceHeight = Dimensions.get("window").height;

export default {
    container: {
        backgroundColor: "transparent",
    },
    container1: {
        marginTop: 0,
        backgroundColor: 'transparent',
        flexDirection: 'column-reverse',
        justifyContent: 'space-between',

    },
    imageContainer2: {
        alignContent: 'center',
        width: 50,
        height: 50,
        resizeMode: 'contain',
        marginTop: -10,
    },
    imageContainer3: {
        alignContent: 'center',
        width: 40,
        height: 40,
        resizeMode: 'contain',
        borderRadius: 5,
    },
    labelFalci: {
        color: 'black',
        fontSize: 14,
        marginBottom: 0,
        marginTop: 10,
        fontFamily: 'Fondamento-Regular',
    },
    labelFalci2: {
        color: 'black',
        fontSize: 14,
        marginBottom: 0,
        marginTop: 10,
        marginLeft: 5,
        fontFamily: 'Fondamento-Regular',
    },
    labelDakika: {
        fontFamily: 'Roboto-Medium',

        fontSize: 16,
        color: '#b8437f',
        marginLeft: 20,
        marginTop: 15,
    },
    labelDakika1: {
        fontFamily: 'Roboto-Medium',
        fontSize: 9,
        color: '#b8437f',
        marginLeft: 22,
        marginTop: -2,
    },
    labelDakika2: {
        fontFamily: 'Roboto-Medium',
        fontSize: 12,
        // color: '#b8437f',
        marginLeft: 12,
        marginTop: 10,
    },
    labelDakika3: {
        fontFamily: 'Roboto-Medium',
        fontSize: 9,
        //  color: '#b8437f',
        marginLeft: 15,
        marginTop: -2,
    },
    contentWrap: {
        flex: 1,
        padding: 15,
        marginTop: 100,
        marginLeft: 0,
        marginRight: 0,
        marginBottom: 0,
        backgroundColor: '#e1e1e1',
        // borderRadius: 5,
    },
    mb: {
        marginBottom: 5,
        marginLeft: 10,
        marginRight: 10,
        marginTop: 5,
    },
    container2: {
        flex: 1,
        backgroundColor: 'transparent',
        flexDirection: 'row',
    },
    buttonIco: {
        marginTop: 10,
        marginLeft: 30,
        marginRight: 30,
        width: 40,
        height: 40,
        resizeMode: "contain"
    },
    buttonLoginIconorta: {
        marginBottom: 20,
        height: 90,
        width: 150,
        resizeMode: "contain",
    },
    container2: {
        flex: 1,
        backgroundColor: 'transparent',
        flexDirection: 'row',
    },
    imageContainer3: {
        alignContent: 'center',
        width: 40,
        height: 40,
        resizeMode: 'contain',
    },
    labelGenelIstaistikler: {
        // color: '#999',
        fontSize: 20,
        marginBottom: 12,
        fontFamily: 'Fondamento-Regular',
    },
    labelFalciSiyah: {
        //color: '#b7417e',

        fontSize: 20,
        marginLeft: 12,
        fontFamily: 'Roboto-Medium',
    },

    labelFalcinote: {
        color: '#999',
        //  fontWeight: 'bold',
        fontSize: 12,
        marginBottom: 5,
        marginLeft: 10,
        marginTop: 10,
        fontFamily: 'Roboto-Light',
    },
    labelFalcinote2: {
        color: '#b8437f',
        //  fontWeight: 'bold',
        fontSize: 10,
        marginBottom: 12,
        marginLeft: 170,
        marginRight: 5,
        fontFamily: 'Roboto-Regular',
    },
    labelthin: {
        color: 'white',
        // fontWeight: 'bold',
        fontSize: 9,
        marginBottom: 0,
        marginLeft: 90,
        marginTop: -80,
        fontFamily: 'Roboto-Light',
    },
    labelthin2: {
        color: 'white',
        fontSize: 12,
        marginBottom: 0,
        marginLeft: 80,
        marginTop: 0,
        fontFamily: 'Roboto-Lightitalic',
    },
    labelthin3: {
        color: '#999',
        // fontWeight: 'bold',
        fontSize: 10,
        marginBottom: 0,
        marginLeft: 0,
        marginTop: -5,
        fontFamily: 'Roboto-Lightitalic',
    },
    labelthin4: {
        color: 'white',
        // fontWeight: 'bold',
        fontSize: 9,
        marginBottom: 0,
        marginLeft: 5,
        marginTop: 0,
        fontFamily: 'Roboto-Light',
    },
    labelthin5: {
        color: '#999',
        // fontWeight: 'bold',
        fontSize: 10,
        marginBottom: 0,
        marginLeft: 0,
        marginTop: 0,
        fontFamily: 'Roboto-Lightitalic',
    },
    labelFiyat: {
        //  fontWeight: 'bold',
        fontSize: 18,
        marginBottom: 8,
        fontFamily: 'Roboto-Bold',
        marginLeft: 10,
    },
    labelAciklama: {
        color: '#8b8b8b',
        fontSize: 16,
        marginBottom: 8,
        fontFamily: 'Roboto-Lightitalic',
        marginLeft: 10,
    },
    labelAciklama2: {
        color: '#605f5f',
        fontSize: 14,
        marginBottom: 8,
        fontFamily: 'Roboto-Light',
        marginLeft: 10,
    },
    labelFiyat2: {
        //  fontWeight: 'bold',
        fontSize: 13,
        marginBottom: 5,
        fontFamily: 'Roboto-Bold',
        marginLeft: -130,
    },
    imageContainer: {
        flex: 1,

        width: null,
        height: null,
        resizeMode: 'contain',
    },
    logoContainer: {
        alignSelf: 'center',
        width: null,
        height: null,
        flex: 1,
    },
    labelFalcibeyaz: {
        color: 'white',
        fontWeight: 'bold',
        fontSize: 22,
        marginBottom: 0,
        fontFamily: 'Fondamento-Regular',
        marginLeft: 80,
        marginTop: 0,

    },
    labelFalcibeyazthin: {
        color: 'white',
        fontSize: 12,
        marginBottom: 0,
        fontFamily: 'Fondamento-Regular',
        marginLeft: 90,
        marginTop: -10,
    },
    labelFalcibeyazthin2: {
        color: 'white',
        fontSize: 12,
        marginBottom: 0,
        fontFamily: 'Fondamento-Regular',
        marginLeft: 190,
        marginTop: -18,
    },
}